name: CI-MySQL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: install mysql server
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          sudo apt-get install -y mysql-server
          sudo service mysqld start
          
      - name: install mysql server
        run: |
          mysql -V
          mysql -u root test -e"show tables"
