name: CI-MySQL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo /home/runner/work/testaction-mysql/testaction-mysql

      - name: install mysql server
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo sudo apt-get install -y mysql-server
          
      - name: start mysql server
        run: |    
          sudo whereis mysqld
          sudo whereis my.cnf
          sudo mysqld -V
          sudo netstat -antop | grep LISTEN
          ls -al /etc/my*
          echo cat /etc/alternatives/my.cnf
          cat /etc/alternatives/my.cnf
          echo cat /etc/mysql.cnf
          echo ls -al /etc/mysql/conf.d
          ls -al /etc/mysql/conf.d
          echo cat /etc/mysql/conf.d/mysql.cnf
          cat /etc/mysql/conf.d/mysql.cnf
          echo ls -al /etc/mysql/mysql.conf.d/
          ls -al /etc/mysql/mysql.conf.d/
          echo cat /etc/mysql/mysql.conf.d/mysqld.cnf
          cat /etc/mysql/mysql.conf.d/mysqld.cnf
          sudo echo "[mysqld]" > ~/.mysql.cnf
          sudo echo "datadir		= /tmp/mydata" >> ~/.mysql.cnf
          echo sudo mysqld --initialize-insecure --user=mysql --datadir=/tmp/mydata
          sudo mysqld --initialize-insecure --user=mysql --datadir=/tmp/mydata
          echo sudo mysqld start --user=mysql --datadir=/tmp/mydata
          sudo mysqld start --user=mysql --datadir=/tmp/mydata
          
      - name: test mysql server
        run: |
          mysql -V
          mysql -u root test -e"show tables"
