name: CI-MySQL

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo /home/runner/work/testaction-mysql/testaction-mysql

      - name: install mysql server
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          sudo apt-get install -y mysql-server
          
      - name: start mysql server
        run: |    
          sudo whereis mysqld
          sudo whereis my.cnf
          sudo mysqld -V
          sudo netstat -antop | grep LISTEN
          ls -al /etc/my*
          echo cat /etc/alternatives/my.cnf
          cat /etc/alternatives/my.cnf
          echo cat /etc/mysql.cnf
          cat /etc/mysql.cnf
          ls -al /etc/mysql.conf.d
          sudo mysqld --initialize-insecure
          sudo mysqld start
          
      - name: test mysql server
        run: |
          mysql -V
          mysql -u root test -e"show tables"
